### PR TITLE
linguist repos

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by askeblad** [comment]
@jaspervdj rendering [here](https://github.com/vaerksted/meta)

**Comment by gbaz** [comment]
Basing this on linguist doesn't make much sense. Lots of these repos are going to be wrongly classified -- for example haskell repos that happen to bundle c++ source as foreign imports. (and even if linguist did classify things correctly, it wouldn't be a useful way of organizing any meaningful information)

**Comment by askeblad** [comment]
_cf_: [How Linguist works](https://github.com/github/linguist/blob/master/docs/how-linguist-works.md)

**Comment by askeblad** [comment]
@gbaz you neglect the usefulness of the PR, _i.e._ bookmarking the page for a list of repos

**Comment by chessai** [comment]
> @gbaz you neglect the usefulness of the PR, _i.e._ bookmarking the page for a list of repos

I agree with @gbaz, this use of linguist doesn't really make sense to me. Bookmarking repos can be done in a different way, and it certainly needs to be done in a way that is more useful than just scrolling or searching on the Haskell GitHub org.

**Comment by askeblad** [comment]
https://github.com/haskell/meta/issues/1#issuecomment-1087974321

repos w/URLs

**Comment by askeblad** [comment]
well a meager idea would be to add it to the repo as linguist.md

**Pull request closed without merging**
